study_dbt:
  outputs:
    dev:
      dbname: postgres
      host: 172.17.0.1
      pass: my_pwd
      port: 5432
      schema: public
      threads: 1
      type: postgres
      user: new_user
  target: dev
